FROM node:alpine

WORKDIR /app

RUN apk update
RUN apk add --no-cache bash 
RUN apk add --no-cache rsync

RUN npm install @angular/cli
RUN npm install @ionic/cli

RUN npm install

CMD ["serve","--poll 200 ", "--host 0.0.0.0","--external", "--no-open"]

